apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default  # Change namespace if needed
  labels:
    app: api-gateway
spec:
  type: ClusterIP  # Change to LoadBalancer if external access is needed
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 8080        # Exposed service port
    targetPort: 8080  # Container port
    nodePort: 30001
  type: NodePort  
