apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default  # Change namespace if needed
  labels:
    app: api-gateway
spec:
  replicas: 3  # Adjust the replica count as needed
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: 0964279710/api-gateway:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always
