apiVersion: v1
kind: Service
metadata:
  name: service-discovery-service
  namespace: default  # Change namespace if needed
  labels:
    app: service-discovery
spec:
  selector:
    app: service-discovery
  ports:
  - protocol: TCP
    port: 8761        # Exposed service port
    targetPort: 8761  # Container port
    nodePort: 30002
  type: NodePort  
