apiVersion: v1
kind: Service
metadata:
  name: service-discovery-external
  namespace: default  # Change namespace if needed
  labels:
    app: service-discovery
spec:
  type: NodePort  
  selector:
    app: service-discovery
  ports:
  - protocol: TCP
    port: 8761        # Exposed service port
    targetPort: 8761  # Container port
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-internal
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      address: 0.0.0.0