apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: default  # Change namespace if needed
  labels:
    app: service-discovery
spec:
  replicas: 2  # Adjust the replica count as needed
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery-container
        image: 0964279710/service-discovery:latest
        ports:
        - containerPort: 8761
        imagePullPolicy: Always
      restartPolicy: Always
