apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        kubernetes.io/hostname: workernode1
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: jnlp
          containerPort: 50000
        env:
        - name: JENKINS_OPTS
          value: "--prefix=/jenkins"  
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-21-openjdk-amd64"  
        volumeMounts:
          - name: jenkins-data
            mountPath: /var/jenkins_home
          - name: java-home
            mountPath: /usr/lib/jvm/java-21-openjdk-amd64  
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc    
