apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: default  # Change namespace if needed
  labels:
    app: authorization-service
spec:
  type: NodePort  
  selector:
    app: authorization-service
  ports:
  - protocol: TCP
    port: 8100       
    targetPort: 8100 
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: default  # Change namespace if needed
  labels:
    app: authorization-service
spec:
  type: ClusterIP  
  selector:
    app: authorization-service
  ports:
  - protocol: TCP
    port: 8100       
    targetPort: 8100 