apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: default  # Change namespace if needed
  labels:
    app: authorization-service
spec:
  type: ClusterIP  
  selector:
    app: authorization-service
  ports:
  - protocol: TCP
    port: 80       
    targetPort: 8100 