apiVersion: v1
kind: Service
metadata:
  name: english-tracker-fe-service
spec:
  type: NodePort
  selector:
    app: english-tracker-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080